package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_library")

sass_library(
    name = "_colors_scss",
    srcs = ["_colors.scss"],
)

sass_library(
    name = "_fonts_scss",
    srcs = ["_fonts.scss"],
)
